[package]
name = "vvdecli"
version = "0.6.0"
edition = "2021"
authors = ["Carlos Bentzen <cadubentzen@gmail.com>"]
description = "CLI application for decoding VVC bitstreams"
license = "BSD-3-Clause-Clear"
repository = "https://github.com/cadubentzen/vvdec-rs"
exclude = ["tests/"]

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
thiserror = "1"
vvdec = { path = "..", version = "0.6.0" }
y4m = "0.8"

[dev-dependencies]
assert_cmd = "2"

[features]
vendored = ["vvdec/vendored"]
