[package]
name = "vvdec-sys"
version = "0.3.2"
edition = "2021"
links = "vvdec"
authors = ["Carlos Bentzen <cadubentzen@gmail.com>"]
description = "Rust unsafe bindings for VVdeC"
license = "BSD-3-Clause-Clear"
repository = "https://github.com/cadubentzen/vvdec-rs"

[build-dependencies]
bindgen = "0.68"
cmake = "0.1"
pkg-config = "0.3"
