name: "test"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/cadubentzen/vvdec-rs-devcontainer
          runCmd: |
            cargo test --workspace

  test-windows:
    runs-on: windows-latest
    env:
      SYSTEM_DEPS_LIBVVDEC_BUILD_INTERNAL: auto
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install pkg-config using Chocolatey
        run: choco install pkgconfiglite -y

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run tests
        run: cargo test --workspace

  msrv:
    runs-on: ubuntu-latest
    env:
      SYSTEM_DEPS_LIBVVDEC_BUILD_INTERNAL: auto
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install pkg-config using apt
        run: sudo apt-get install -y pkg-config

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.80.1
          override: true

      - name: Check rustc version
        run: rustc --version

      - name: Check cargo version
        run: cargo --version

      - name: Build
        run: cargo build --workspace
